version: '3.8'

services:
  db:
    image: postgres:15
    container_name: sgcpd_db
    restart: always
    ports:
      - "5435:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: sgcpd_db
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./init-db:/docker-entrypoint-initdb.d

volumes:
  pgdata: